import type { Spot } from "./types";

export const REGIONS = [
  "Manche & Nord",
  "Bretagne",
  "Atlantique Nord",
  "Côte d'Argent",
  "Pays Basque",
  "Méditerranée",
] as const;

export const REGION_EMOJI: Record<string, string> = {
  "Manche & Nord": "🏰",
  "Bretagne": "🌬️",
  "Atlantique Nord": "🐚",
  "Côte d'Argent": "🏖️",
  "Pays Basque": "🏄",
  "Méditerranée": "☀️",
};

export const SPOTS: Spot[] = [
  // ==================== MANCHE & NORD ====================
  { slug: "wissant", name: "Wissant", shortName: "Wissant", region: "Manche & Nord", department: "Pas-de-Calais", lat: 50.887, lon: 1.662, offshore: 180, level: "intermediate", type: "Beach break", description: "Plage sauvage entre les caps Gris-Nez et Blanc-Nez. Exposée aux houles NW, fonctionne avec un fort vent de sud." },
  { slug: "hardelot", name: "Hardelot-Plage", shortName: "Hardelot", region: "Manche & Nord", department: "Pas-de-Calais", lat: 50.633, lon: 1.583, offshore: 90, level: "beginner", type: "Beach break", description: "Longue plage de sable accessible. Surf de fortune par grosse houle d'ouest." },
  { slug: "le-touquet", name: "Le Touquet", shortName: "Le Touquet", region: "Manche & Nord", department: "Pas-de-Calais", lat: 50.523, lon: 1.586, offshore: 90, level: "beginner", type: "Beach break", description: "Longue plage facile, idéale pour débuter quand la houle entre dans la Manche." },
  { slug: "etretat", name: "Étretat", shortName: "Étretat", region: "Manche & Nord", department: "Seine-Maritime", lat: 49.708, lon: 0.205, offshore: 135, level: "intermediate", type: "Beach break / galets", description: "Spot mythique sous les falaises. Vagues de qualité par grosse houle NW, fond de galets." },
  { slug: "veulettes", name: "Veulettes-sur-Mer", shortName: "Veulettes", region: "Manche & Nord", department: "Seine-Maritime", lat: 49.857, lon: 0.595, offshore: 180, level: "beginner", type: "Beach break / galets", description: "Plage de galets normande, surfable par houle NW établie. Communauté locale active." },
  { slug: "ouistreham", name: "Ouistreham - Riva-Bella", shortName: "Ouistreham", region: "Manche & Nord", department: "Calvados", lat: 49.287, lon: -0.258, offshore: 180, level: "beginner", type: "Beach break", description: "Plage longue et plate, parfaite pour les débutants. Surfable surtout en automne-hiver." },
  { slug: "asnelles", name: "Asnelles (Gold Beach)", shortName: "Asnelles", region: "Manche & Nord", department: "Calvados", lat: 49.336, lon: -0.567, offshore: 180, level: "beginner", type: "Beach break", description: "Plage du débarquement, fond doux. Surfable par houle NW, école et bonne ambiance." },
  { slug: "siouville", name: "Siouville-Hague", shortName: "Siouville", region: "Manche & Nord", department: "Manche", lat: 49.555, lon: -1.842, offshore: 90, level: "intermediate", type: "Beach break", description: "Le spot phare de Normandie. Fonctionne avec les houles W et NW, capricieux mais peut offrir de très belles sessions." },
  { slug: "vauville", name: "Vauville", shortName: "Vauville", region: "Manche & Nord", department: "Manche", lat: 49.631, lon: -1.839, offshore: 90, level: "intermediate", type: "Beach break", description: "Baie sauvage à côté de Siouville. Houle plus ouverte, ambiance bout du monde." },
  { slug: "le-rozel", name: "Le Rozel", shortName: "Le Rozel", region: "Manche & Nord", department: "Manche", lat: 49.494, lon: -1.871, offshore: 90, level: "intermediate", type: "Beach break", description: "Plage du Cotentin avec dunes spectaculaires. Capricieux mais belles vagues quand ça rentre." },
  { slug: "carolles", name: "Carolles", shortName: "Carolles", region: "Manche & Nord", department: "Manche", lat: 48.733, lon: -1.557, offshore: 180, level: "beginner", type: "Beach break", description: "Baie du Mont-Saint-Michel. Vagues douces, surf occasionnel quand la houle force." },

  // ==================== BRETAGNE ====================
  { slug: "saint-malo", name: "Saint-Malo - Longchamp", shortName: "Saint-Malo", region: "Bretagne", department: "Ille-et-Vilaine", lat: 48.650, lon: -2.020, offshore: 135, level: "beginner", type: "Beach break", description: "Surf à marée basse à côté de la cité corsaire. Spot très accessible et école." },
  { slug: "saint-lunaire", name: "Saint-Lunaire", shortName: "Saint-Lunaire", region: "Bretagne", department: "Ille-et-Vilaine", lat: 48.638, lon: -2.110, offshore: 180, level: "beginner", type: "Beach break", description: "Plage de la Fourberie, surfable à marée basse. Bonne école pour débutants." },
  { slug: "sables-d-or", name: "Sables-d'Or-les-Pins", shortName: "Sables-d'Or", region: "Bretagne", department: "Côtes-d'Armor", lat: 48.642, lon: -2.426, offshore: 180, level: "beginner", type: "Beach break", description: "Longue plage de sable au coeur de la côte d'Émeraude. Vagues régulières par houle NW." },
  { slug: "trestraou", name: "Trestraou - Perros-Guirec", shortName: "Trestraou", region: "Bretagne", department: "Côtes-d'Armor", lat: 48.821, lon: -3.443, offshore: 135, level: "beginner", type: "Beach break", description: "Côte de granit rose. Plage protégée, surfable surtout l'hiver par grosse houle N." },
  { slug: "plouescat", name: "Plouescat - Pors Meur", shortName: "Plouescat", region: "Bretagne", department: "Finistère", lat: 48.671, lon: -4.183, offshore: 180, level: "intermediate", type: "Beach break", description: "Spot de la côte du Léon, exposé aux houles N et NW. Cadre breton authentique." },
  { slug: "goulven", name: "Goulven (La Croix)", shortName: "Goulven", region: "Bretagne", department: "Finistère", lat: 48.625, lon: -4.298, offshore: 180, level: "intermediate", type: "Beach break", description: "Baie de Goulven, dunes et longue plage. Vagues consistantes en hiver." },
  { slug: "le-dossen", name: "Le Dossen (Santec)", shortName: "Le Dossen", region: "Bretagne", department: "Finistère", lat: 48.715, lon: -4.025, offshore: 180, level: "advanced", type: "Beach break", description: "Spot puissant face à l'île de Sieck. Réservé aux confirmés quand la houle N envoie." },
  { slug: "tronoen", name: "Tronoën", shortName: "Tronoën", region: "Bretagne", department: "Finistère", lat: 47.881, lon: -4.318, offshore: 90, level: "intermediate", type: "Beach break", description: "Plage du Pays Bigouden, à côté de La Torche. Bonne alternative quand le spot star sature." },
  { slug: "pors-carn", name: "Pors Carn", shortName: "Pors Carn", region: "Bretagne", department: "Finistère", lat: 47.834, lon: -4.367, offshore: 90, level: "intermediate", type: "Beach break", description: "Plage abritée à côté de La Torche. Vagues plus douces, parfait pour progresser." },
  { slug: "penhors", name: "Penhors", shortName: "Penhors", region: "Bretagne", department: "Finistère", lat: 47.877, lon: -4.334, offshore: 90, level: "intermediate", type: "Beach break", description: "Plage longue du Pays Bigouden, idéale pour des sessions tranquilles en semaine." },
  { slug: "la-torche", name: "La Torche", shortName: "La Torche", region: "Bretagne", department: "Finistère", lat: 47.837, lon: -4.350, offshore: 90, level: "intermediate", type: "Beach break", description: "Spot le plus connu de Bretagne, ultra-exposé aux houles atlantiques. École et compétitions." },
  { slug: "la-palue", name: "La Palue (Crozon)", shortName: "La Palue", region: "Bretagne", department: "Finistère", lat: 48.220, lon: -4.570, offshore: 90, level: "advanced", type: "Beach break", description: "Spot puissant et capricieux de la presqu'île de Crozon. Réservé aux confirmés quand ça envoie." },
  { slug: "lostmarch", name: "Lostmarc'h", shortName: "Lostmarc'h", region: "Bretagne", department: "Finistère", lat: 48.183, lon: -4.544, offshore: 90, level: "intermediate", type: "Beach break", description: "Presqu'île de Crozon, plage sauvage. Vagues puissantes avec une bonne houle W." },
  { slug: "donnant", name: "Donnant - Belle-Île", shortName: "Donnant", region: "Bretagne", department: "Morbihan", lat: 47.339, lon: -3.250, offshore: 90, level: "advanced", type: "Beach break", description: "Le spot star de Belle-Île. Vagues creuses et puissantes, dunes spectaculaires." },
  { slug: "erdeven", name: "Erdeven", shortName: "Erdeven", region: "Bretagne", department: "Morbihan", lat: 47.638, lon: -3.149, offshore: 90, level: "intermediate", type: "Beach break", description: "Longue plage des Mégalithes, exposée aux houles atlantiques. Cadre sauvage." },
  { slug: "penthievre", name: "Penthièvre", shortName: "Penthièvre", region: "Bretagne", department: "Morbihan", lat: 47.555, lon: -3.115, offshore: 0, level: "intermediate", type: "Beach break", description: "Isthme de Quiberon, côte sauvage. Vagues régulières et windsurf à proximité." },
  { slug: "quiberon-port-blanc", name: "Quiberon - Port Blanc", shortName: "Port Blanc", region: "Bretagne", department: "Morbihan", lat: 47.483, lon: -3.120, offshore: 0, level: "intermediate", type: "Beach break", description: "Côte sauvage de la presqu'île de Quiberon. Vagues creuses par houle S/SW." },
  { slug: "plouharnel", name: "Plouharnel - Sainte-Barbe", shortName: "Plouharnel", region: "Bretagne", department: "Morbihan", lat: 47.580, lon: -3.110, offshore: 90, level: "beginner", type: "Beach break", description: "Plage accueillante pour les débutants, bondée en été." },

  // ==================== ATLANTIQUE NORD (Loire-Atlantique, Vendée, Charente-Maritime) ====================
  { slug: "la-govelle", name: "La Govelle (Batz-sur-Mer)", shortName: "La Govelle", region: "Atlantique Nord", department: "Loire-Atlantique", lat: 47.265, lon: -2.526, offshore: 180, level: "beginner", type: "Beach break", description: "Spot familial de la côte sauvage du Croisic. Vagues consistantes en automne." },
  { slug: "saint-brevin", name: "Saint-Brevin-les-Pins", shortName: "Saint-Brevin", region: "Atlantique Nord", department: "Loire-Atlantique", lat: 47.248, lon: -2.173, offshore: 90, level: "beginner", type: "Beach break", description: "Embouchure de la Loire, idéale pour débuter. Vagues douces et longues." },
  { slug: "pornic", name: "Pornic - La Source", shortName: "Pornic", region: "Atlantique Nord", department: "Loire-Atlantique", lat: 47.117, lon: -2.103, offshore: 180, level: "beginner", type: "Beach break", description: "Petite plage abritée du Pays de Retz. Surf rare mais sympa quand la houle entre." },
  { slug: "saint-jean-de-monts", name: "Saint-Jean-de-Monts", shortName: "Saint-Jean-de-Monts", region: "Atlantique Nord", department: "Vendée", lat: 46.793, lon: -2.067, offshore: 90, level: "beginner", type: "Beach break", description: "Longue plage urbaine, idéale en école et en famille." },
  { slug: "sion-sur-l-ocean", name: "Sion-sur-l'Océan", shortName: "Sion", region: "Atlantique Nord", department: "Vendée", lat: 46.755, lon: -2.026, offshore: 90, level: "beginner", type: "Beach break", description: "Plage de Saint-Hilaire-de-Riez. Vagues accessibles et école active." },
  { slug: "bretignolles", name: "Bretignolles-sur-Mer", shortName: "Bretignolles", region: "Atlantique Nord", department: "Vendée", lat: 46.636, lon: -1.865, offshore: 90, level: "intermediate", type: "Beach break", description: "Spot phare de Vendée avec La Sauzaie et la Parée. Vagues régulières et école." },
  { slug: "brem-sur-mer", name: "Brem-sur-Mer", shortName: "Brem", region: "Atlantique Nord", department: "Vendée", lat: 46.605, lon: -1.850, offshore: 90, level: "intermediate", type: "Beach break", description: "Spot des Granges, à côté de Bretignolles. Alternative quand le spot star est saturé." },
  { slug: "les-sables-d-olonne", name: "Les Sables-d'Olonne", shortName: "Les Sables", region: "Atlantique Nord", department: "Vendée", lat: 46.497, lon: -1.790, offshore: 45, level: "beginner", type: "Beach break", description: "Grande Plage urbaine. Surf doux et ambiance station balnéaire." },
  { slug: "longeville-sur-mer", name: "Longeville-sur-Mer", shortName: "Longeville", region: "Atlantique Nord", department: "Vendée", lat: 46.413, lon: -1.529, offshore: 45, level: "intermediate", type: "Beach break", description: "Spot du Rocher, ambiance forestière et dunes. Vagues puissantes par houle SW." },
  { slug: "la-tranche-sur-mer", name: "La Tranche-sur-Mer", shortName: "La Tranche", region: "Atlantique Nord", department: "Vendée", lat: 46.340, lon: -1.435, offshore: 45, level: "beginner", type: "Beach break", description: "Spot familial, parfait pour le longboard et l'apprentissage." },
  { slug: "ile-de-re-le-lizay", name: "Île de Ré - Le Lizay", shortName: "Le Lizay", region: "Atlantique Nord", department: "Charente-Maritime", lat: 46.238, lon: -1.568, offshore: 0, level: "intermediate", type: "Beach break", description: "Pointe nord de l'île, vagues régulières par houle NW. Cadre paradisiaque." },
  { slug: "ile-de-re-conche-baleines", name: "Île de Ré - Conche des Baleines", shortName: "Conche des Baleines", region: "Atlantique Nord", department: "Charente-Maritime", lat: 46.243, lon: -1.561, offshore: 0, level: "intermediate", type: "Beach break", description: "Plage côté ouest de l'île de Ré. Vagues plus consistantes par houle W." },
  { slug: "ile-d-oleron-vert-bois", name: "Île d'Oléron - Vert Bois", shortName: "Vert Bois", region: "Atlantique Nord", department: "Charente-Maritime", lat: 45.883, lon: -1.383, offshore: 90, level: "intermediate", type: "Beach break", description: "Plage la plus exposée d'Oléron. Vagues régulières et école active." },
  { slug: "la-cotiniere", name: "La Cotinière", shortName: "La Cotinière", region: "Atlantique Nord", department: "Charente-Maritime", lat: 45.910, lon: -1.338, offshore: 90, level: "intermediate", type: "Beach break", description: "Plage de la Cotinière à Oléron, ambiance port de pêche." },
  { slug: "saint-trojan", name: "Saint-Trojan-les-Bains", shortName: "Saint-Trojan", region: "Atlantique Nord", department: "Charente-Maritime", lat: 45.832, lon: -1.218, offshore: 135, level: "beginner", type: "Beach break", description: "Sud d'Oléron, plage forestière de Gatseau. Vagues douces et école." },
  { slug: "saint-palais-sur-mer", name: "Saint-Palais-sur-Mer", shortName: "Saint-Palais", region: "Atlantique Nord", department: "Charente-Maritime", lat: 45.640, lon: -1.090, offshore: 90, level: "beginner", type: "Beach break", description: "Plage du Bureau, station familiale. Vagues douces par houle d'ouest." },

  // ==================== CÔTE D'ARGENT (Gironde + Landes) ====================
  { slug: "soulac-sur-mer", name: "Soulac-sur-Mer", shortName: "Soulac", region: "Côte d'Argent", department: "Gironde", lat: 45.518, lon: -1.123, offshore: 90, level: "beginner", type: "Beach break", description: "Pointe du Médoc, plage longue et facile. Idéal pour débuter dans une ambiance balnéaire." },
  { slug: "montalivet", name: "Montalivet", shortName: "Montalivet", region: "Côte d'Argent", department: "Gironde", lat: 45.379, lon: -1.143, offshore: 90, level: "intermediate", type: "Beach break", description: "Plage forestière préservée du Médoc. Vagues puissantes en automne." },
  { slug: "hourtin", name: "Hourtin-Plage", shortName: "Hourtin", region: "Côte d'Argent", department: "Gironde", lat: 45.246, lon: -1.158, offshore: 90, level: "intermediate", type: "Beach break", description: "Station familiale dans la pinède. Vagues consistantes loin de la foule de Lacanau." },
  { slug: "carcans", name: "Carcans-Plage", shortName: "Carcans", region: "Côte d'Argent", department: "Gironde", lat: 45.111, lon: -1.176, offshore: 90, level: "intermediate", type: "Beach break", description: "Plage sauvage juste au nord de Lacanau. Cadre forestier et vagues régulières." },
  { slug: "lacanau", name: "Lacanau", shortName: "Lacanau", region: "Côte d'Argent", department: "Gironde", lat: 45.000, lon: -1.205, offshore: 90, level: "intermediate", type: "Beach break", description: "Spot de référence du Médoc. Étape du tour pro, vagues consistantes." },
  { slug: "le-porge", name: "Le Porge", shortName: "Le Porge", region: "Côte d'Argent", department: "Gironde", lat: 44.883, lon: -1.183, offshore: 90, level: "beginner", type: "Beach break", description: "Plage forestière préservée, sans bétonnage. Beach break long et accessible." },
  { slug: "cap-ferret", name: "Cap Ferret - Horizon", shortName: "Cap Ferret", region: "Côte d'Argent", department: "Gironde", lat: 44.640, lon: -1.250, offshore: 90, level: "intermediate", type: "Beach break", description: "Pointe sauvage face à l'océan. Vagues puissantes et longues." },
  { slug: "biscarrosse", name: "Biscarrosse-Plage", shortName: "Biscarrosse", region: "Côte d'Argent", department: "Landes", lat: 44.435, lon: -1.260, offshore: 90, level: "intermediate", type: "Beach break", description: "Premier spot landais en venant du nord. Vagues régulières, école et compétitions." },
  { slug: "mimizan", name: "Mimizan", shortName: "Mimizan", region: "Côte d'Argent", department: "Landes", lat: 44.205, lon: -1.300, offshore: 90, level: "beginner", type: "Beach break", description: "Plage du Courant, accueillante et bien orientée. École reconnue." },
  { slug: "contis", name: "Contis", shortName: "Contis", region: "Côte d'Argent", department: "Landes", lat: 44.082, lon: -1.323, offshore: 90, level: "intermediate", type: "Beach break", description: "Spot des Landes préservé, cadre forestier. Vagues sauvages et tranquilles." },
  { slug: "cap-de-l-homy", name: "Cap-de-l'Homy (Lit-et-Mixe)", shortName: "Cap-de-l'Homy", region: "Côte d'Argent", department: "Landes", lat: 44.030, lon: -1.341, offshore: 90, level: "intermediate", type: "Beach break", description: "Petit village à dunes, ambiance authentique landaise. Vagues consistantes." },
  { slug: "saint-girons-plage", name: "Saint-Girons-Plage", shortName: "Saint-Girons", region: "Côte d'Argent", department: "Landes", lat: 43.952, lon: -1.358, offshore: 90, level: "intermediate", type: "Beach break", description: "Spot sauvage à côté de Moliets. Cadre préservé, vagues puissantes." },
  { slug: "moliets", name: "Moliets-Plage", shortName: "Moliets", region: "Côte d'Argent", department: "Landes", lat: 43.857, lon: -1.383, offshore: 90, level: "intermediate", type: "Beach break", description: "Spot reconnu, étape historique du tour pro. Vagues creuses et école dynamique." },
  { slug: "vieux-boucau", name: "Vieux-Boucau-les-Bains", shortName: "Vieux-Boucau", region: "Côte d'Argent", department: "Landes", lat: 43.794, lon: -1.404, offshore: 90, level: "intermediate", type: "Beach break", description: "Plage du Penon, ambiance village basque. Vagues régulières avec péages occasionnels." },
  { slug: "seignosse", name: "Seignosse - Les Bourdaines", shortName: "Seignosse", region: "Côte d'Argent", department: "Landes", lat: 43.690, lon: -1.435, offshore: 90, level: "intermediate", type: "Beach break", description: "Spot mondialement reconnu. Vagues puissantes, étape du tour pro, peak local." },
  { slug: "hossegor", name: "Hossegor - La Gravière", shortName: "Hossegor", region: "Côte d'Argent", department: "Landes", lat: 43.670, lon: -1.440, offshore: 90, level: "advanced", type: "Beach break / fosse", description: "Le tube break le plus célèbre d'Europe. Étape WSL, vagues creuses et puissantes." },
  { slug: "capbreton", name: "Capbreton - Le Santocha", shortName: "Capbreton", region: "Côte d'Argent", department: "Landes", lat: 43.645, lon: -1.447, offshore: 90, level: "intermediate", type: "Beach break / jetée", description: "Spot abrité par la jetée, fonctionne quand Hossegor sature. Belle vague droite." },

  // ==================== PAYS BASQUE ====================
  { slug: "anglet-cavaliers", name: "Anglet - Les Cavaliers", shortName: "Cavaliers", region: "Pays Basque", department: "Pyrénées-Atlantiques", lat: 43.510, lon: -1.524, offshore: 90, level: "intermediate", type: "Beach break", description: "Plage star d'Anglet, beach break puissant. Étape historique de compétitions." },
  { slug: "anglet", name: "Anglet - Chambre d'Amour", shortName: "Chambre d'Amour", region: "Pays Basque", department: "Pyrénées-Atlantiques", lat: 43.485, lon: -1.550, offshore: 90, level: "intermediate", type: "Beach break", description: "Sept plages en enfilade. Très accessible, école et compétitions." },
  { slug: "biarritz-grande-plage", name: "Biarritz - Grande Plage", shortName: "Grande Plage", region: "Pays Basque", department: "Pyrénées-Atlantiques", lat: 43.487, lon: -1.561, offshore: 90, level: "beginner", type: "Beach break", description: "Le coeur de Biarritz, sous le Casino. Vagues douces, ambiance ville." },
  { slug: "biarritz", name: "Biarritz - Côte des Basques", shortName: "Côte des Basques", region: "Pays Basque", department: "Pyrénées-Atlantiques", lat: 43.480, lon: -1.565, offshore: 110, level: "beginner", type: "Beach break", description: "Berceau du surf européen. Vague douce idéale pour le longboard et la progression." },
  { slug: "bidart", name: "Bidart - Erretegia", shortName: "Bidart", region: "Pays Basque", department: "Pyrénées-Atlantiques", lat: 43.443, lon: -1.589, offshore: 90, level: "intermediate", type: "Beach break", description: "Crique pittoresque encadrée de falaises. Vague régulière dans un cadre superbe." },
  { slug: "guethary", name: "Guéthary - Parlementia", shortName: "Guéthary", region: "Pays Basque", department: "Pyrénées-Atlantiques", lat: 43.425, lon: -1.608, offshore: 135, level: "advanced", type: "Reef break", description: "Vague de récif puissante, pour confirmés uniquement quand ça envoie 3m+." },
  { slug: "lafitenia", name: "Saint-Jean-de-Luz - Lafitenia", shortName: "Lafitenia", region: "Pays Basque", department: "Pyrénées-Atlantiques", lat: 43.397, lon: -1.640, offshore: 135, level: "advanced", type: "Reef break", description: "Belle vague de droite sur fond de récif, l'un des spots techniques du Pays Basque." },
  { slug: "erromardie", name: "Erromardie", shortName: "Erromardie", region: "Pays Basque", department: "Pyrénées-Atlantiques", lat: 43.408, lon: -1.642, offshore: 135, level: "beginner", type: "Beach break", description: "Spot familial entre Saint-Jean-de-Luz et Guéthary. Vague douce et école." },
  { slug: "hendaye", name: "Hendaye", shortName: "Hendaye", region: "Pays Basque", department: "Pyrénées-Atlantiques", lat: 43.370, lon: -1.780, offshore: 180, level: "beginner", type: "Beach break", description: "Grande baie protégée, vagues douces. Le spot famille du Pays Basque." },

  // ==================== MÉDITERRANÉE ====================
  { slug: "leucate", name: "Leucate-Plage", shortName: "Leucate", region: "Méditerranée", department: "Aude", lat: 42.918, lon: 3.052, offshore: 270, level: "intermediate", type: "Beach break", description: "Spot exposé aux houles de SE, surf rare mais belle vague en automne-hiver." },
  { slug: "sainte-marie-la-mer", name: "Sainte-Marie-la-Mer", shortName: "Sainte-Marie", region: "Méditerranée", department: "Pyrénées-Orientales", lat: 42.728, lon: 3.027, offshore: 270, level: "intermediate", type: "Beach break", description: "Catalogne française, plage longue. Surf possible par tempête de SE." },
  { slug: "cap-d-agde", name: "Cap d'Agde - La Tamarissière", shortName: "Cap d'Agde", region: "Méditerranée", department: "Hérault", lat: 43.283, lon: 3.466, offshore: 0, level: "intermediate", type: "Beach break", description: "Plage longue ouverte sur le Golfe du Lion. Vague par tempête SE et mistral retombant." },
  { slug: "marseille-prado", name: "Marseille - Le Prado", shortName: "Le Prado", region: "Méditerranée", department: "Bouches-du-Rhône", lat: 43.263, lon: 5.364, offshore: 0, level: "intermediate", type: "Beach break", description: "Plage urbaine de Marseille. Surfable quand le Mistral retombe et que la houle SW arrive." },
  { slug: "le-brusc", name: "Le Brusc - Six-Fours", shortName: "Le Brusc", region: "Méditerranée", department: "Var", lat: 43.066, lon: 5.805, offshore: 0, level: "intermediate", type: "Beach break", description: "Spot du Var qui fonctionne par tempête de SE/SW. Sessions rares mais belles." },
  { slug: "almanarre", name: "L'Almanarre - Hyères", shortName: "Almanarre", region: "Méditerranée", department: "Var", lat: 43.084, lon: 6.137, offshore: 90, level: "intermediate", type: "Beach break", description: "Spot connu pour le windsurf mais surfable par tempête W. Cadre lagune." },
];

export function getSpotBySlug(slug: string): Spot | undefined {
  return SPOTS.find((s) => s.slug === slug);
}
