import type { Spot } from "./types";

export const REGIONS = [
  "Manche & Nord",
  "Bretagne",
  "Atlantique Nord",
  "Côte d'Argent",
  "Pays Basque",
  "Méditerranée",
] as const;

export const REGION_EMOJI: Record<string, string> = {
  "Manche & Nord": "🏰",
  "Bretagne": "🌬️",
  "Atlantique Nord": "🐚",
  "Côte d'Argent": "🏖️",
  "Pays Basque": "🏄",
  "Méditerranée": "☀️",
};

export const SPOTS: Spot[] = [
  // Côte d'Opale & Manche
  {
    slug: "wissant",
    name: "Wissant",
    shortName: "Wissant",
    region: "Manche & Nord",
    department: "Pas-de-Calais",
    lat: 50.887, lon: 1.662, offshore: 180,
    level: "intermediate",
    type: "Beach break",
    description: "Plage sauvage entre les caps Gris-Nez et Blanc-Nez. Spot exposé aux houles de NW, fonctionne avec un fort vent de sud.",
  },
  {
    slug: "le-touquet",
    name: "Le Touquet",
    shortName: "Le Touquet",
    region: "Manche & Nord",
    department: "Pas-de-Calais",
    lat: 50.523, lon: 1.586, offshore: 90,
    level: "beginner",
    type: "Beach break",
    description: "Longue plage facile, idéale pour débuter quand la houle entre dans la Manche.",
  },
  {
    slug: "etretat",
    name: "Étretat",
    shortName: "Étretat",
    region: "Manche & Nord",
    department: "Seine-Maritime",
    lat: 49.708, lon: 0.205, offshore: 135,
    level: "intermediate",
    type: "Beach break / galets",
    description: "Spot mythique sous les falaises. Vagues de qualité par grosse houle NW, fond de galets.",
  },
  {
    slug: "ouistreham",
    name: "Ouistreham - Riva-Bella",
    shortName: "Ouistreham",
    region: "Manche & Nord",
    department: "Calvados",
    lat: 49.287, lon: -0.258, offshore: 180,
    level: "beginner",
    type: "Beach break",
    description: "Plage longue et plate, parfaite pour les débutants. Surfable surtout en automne-hiver.",
  },
  {
    slug: "siouville",
    name: "Siouville-Hague",
    shortName: "Siouville",
    region: "Manche & Nord",
    department: "Manche",
    lat: 49.555, lon: -1.842, offshore: 90,
    level: "intermediate",
    type: "Beach break",
    description: "Le spot phare de Normandie. Fonctionne avec les houles W et NW, capricieux mais peut offrir de très belles sessions.",
  },
  {
    slug: "vauville",
    name: "Vauville",
    shortName: "Vauville",
    region: "Manche & Nord",
    department: "Manche",
    lat: 49.631, lon: -1.839, offshore: 90,
    level: "intermediate",
    type: "Beach break",
    description: "Baie sauvage à côté de Siouville. Houle plus ouverte, ambiance bout du monde.",
  },

  // Bretagne
  {
    slug: "saint-malo",
    name: "Saint-Malo - Longchamp",
    shortName: "Saint-Malo",
    region: "Bretagne",
    department: "Ille-et-Vilaine",
    lat: 48.650, lon: -2.020, offshore: 135,
    level: "beginner",
    type: "Beach break",
    description: "Surf à marée basse à côté de la cité corsaire. Spot très accessible et école.",
  },
  {
    slug: "lostmarch",
    name: "Lostmarc'h",
    shortName: "Lostmarc'h",
    region: "Bretagne",
    department: "Finistère",
    lat: 48.183, lon: -4.544, offshore: 90,
    level: "intermediate",
    type: "Beach break",
    description: "Presqu'île de Crozon, plage sauvage. Vagues puissantes avec une bonne houle W.",
  },
  {
    slug: "la-palue",
    name: "La Palue (Crozon)",
    shortName: "La Palue",
    region: "Bretagne",
    department: "Finistère",
    lat: 48.220, lon: -4.570, offshore: 90,
    level: "advanced",
    type: "Beach break",
    description: "Spot puissant et capricieux de la presqu'île de Crozon. Réservé aux confirmés quand ça envoie.",
  },
  {
    slug: "penhors",
    name: "Penhors",
    shortName: "Penhors",
    region: "Bretagne",
    department: "Finistère",
    lat: 47.877, lon: -4.334, offshore: 90,
    level: "intermediate",
    type: "Beach break",
    description: "Plage longue du Pays Bigouden, idéale pour des sessions tranquilles en semaine.",
  },
  {
    slug: "la-torche",
    name: "La Torche",
    shortName: "La Torche",
    region: "Bretagne",
    department: "Finistère",
    lat: 47.837, lon: -4.350, offshore: 90,
    level: "intermediate",
    type: "Beach break",
    description: "Spot le plus connu de Bretagne, ultra-exposé aux houles atlantiques. Souvent gros et fort, école et compétitions.",
  },
  {
    slug: "quiberon-port-blanc",
    name: "Quiberon - Port Blanc",
    shortName: "Port Blanc",
    region: "Bretagne",
    department: "Morbihan",
    lat: 47.483, lon: -3.120, offshore: 0,
    level: "intermediate",
    type: "Beach break",
    description: "Côte sauvage de la presqu'île de Quiberon. Vagues creuses par houle S/SW.",
  },
  {
    slug: "plouharnel",
    name: "Plouharnel",
    shortName: "Plouharnel",
    region: "Bretagne",
    department: "Morbihan",
    lat: 47.580, lon: -3.110, offshore: 90,
    level: "beginner",
    type: "Beach break",
    description: "Plage de Sainte-Barbe, accueillante pour les débutants et bondée en été.",
  },

  // Atlantique Nord (Loire, Vendée, Charente)
  {
    slug: "saint-brevin",
    name: "Saint-Brevin-les-Pins",
    shortName: "Saint-Brevin",
    region: "Atlantique Nord",
    department: "Loire-Atlantique",
    lat: 47.248, lon: -2.173, offshore: 90,
    level: "beginner",
    type: "Beach break",
    description: "Embouchure de la Loire, idéale pour débuter. Vagues douces et longues.",
  },
  {
    slug: "bretignolles",
    name: "Bretignolles-sur-Mer",
    shortName: "Bretignolles",
    region: "Atlantique Nord",
    department: "Vendée",
    lat: 46.636, lon: -1.865, offshore: 90,
    level: "intermediate",
    type: "Beach break",
    description: "Spot phare de Vendée avec La Sauzaie et la Parée. Vagues régulières et école.",
  },
  {
    slug: "les-sables-d-olonne",
    name: "Les Sables-d'Olonne",
    shortName: "Les Sables",
    region: "Atlantique Nord",
    department: "Vendée",
    lat: 46.497, lon: -1.790, offshore: 45,
    level: "beginner",
    type: "Beach break",
    description: "Grande Plage urbaine. Surf doux et ambiance station balnéaire.",
  },
  {
    slug: "la-tranche-sur-mer",
    name: "La Tranche-sur-Mer",
    shortName: "La Tranche",
    region: "Atlantique Nord",
    department: "Vendée",
    lat: 46.340, lon: -1.435, offshore: 45,
    level: "beginner",
    type: "Beach break",
    description: "Spot familial, parfait pour le longboard et l'apprentissage.",
  },
  {
    slug: "ile-de-re-le-lizay",
    name: "Île de Ré - Le Lizay",
    shortName: "Île de Ré",
    region: "Atlantique Nord",
    department: "Charente-Maritime",
    lat: 46.238, lon: -1.568, offshore: 0,
    level: "intermediate",
    type: "Beach break",
    description: "Pointe nord de l'île, vagues régulières par houle NW. Cadre paradisiaque.",
  },
  {
    slug: "ile-d-oleron-vert-bois",
    name: "Île d'Oléron - Vert Bois",
    shortName: "Vert Bois",
    region: "Atlantique Nord",
    department: "Charente-Maritime",
    lat: 45.883, lon: -1.383, offshore: 90,
    level: "intermediate",
    type: "Beach break",
    description: "Plage la plus exposée d'Oléron. Vagues régulières et école active.",
  },
  {
    slug: "la-cotiniere",
    name: "La Cotinière",
    shortName: "La Cotinière",
    region: "Atlantique Nord",
    department: "Charente-Maritime",
    lat: 45.910, lon: -1.338, offshore: 90,
    level: "intermediate",
    type: "Beach break",
    description: "Plage de la Cotinière à Oléron, ambiance port de pêche.",
  },

  // Côte d'Argent (Gironde + Landes)
  {
    slug: "cap-ferret",
    name: "Cap Ferret - Horizon",
    shortName: "Cap Ferret",
    region: "Côte d'Argent",
    department: "Gironde",
    lat: 44.640, lon: -1.250, offshore: 90,
    level: "intermediate",
    type: "Beach break",
    description: "Pointe sauvage face à l'océan. Vagues puissantes et longues.",
  },
  {
    slug: "le-porge",
    name: "Le Porge",
    shortName: "Le Porge",
    region: "Côte d'Argent",
    department: "Gironde",
    lat: 44.883, lon: -1.183, offshore: 90,
    level: "beginner",
    type: "Beach break",
    description: "Plage forestière préservée, sans bétonnage. Beach break long et accessible.",
  },
  {
    slug: "lacanau",
    name: "Lacanau",
    shortName: "Lacanau",
    region: "Côte d'Argent",
    department: "Gironde",
    lat: 45.000, lon: -1.205, offshore: 90,
    level: "intermediate",
    type: "Beach break",
    description: "Spot de référence du Médoc. Étape du tour pro, vagues consistantes.",
  },
  {
    slug: "mimizan",
    name: "Mimizan",
    shortName: "Mimizan",
    region: "Côte d'Argent",
    department: "Landes",
    lat: 44.205, lon: -1.300, offshore: 90,
    level: "beginner",
    type: "Beach break",
    description: "Plage du Courant, accueillante et bien orientée. École reconnue.",
  },
  {
    slug: "seignosse",
    name: "Seignosse - Les Bourdaines",
    shortName: "Seignosse",
    region: "Côte d'Argent",
    department: "Landes",
    lat: 43.690, lon: -1.435, offshore: 90,
    level: "intermediate",
    type: "Beach break",
    description: "Spot mondialement reconnu. Vagues puissantes, étape du tour pro, peak local.",
  },
  {
    slug: "hossegor",
    name: "Hossegor - La Gravière",
    shortName: "Hossegor",
    region: "Côte d'Argent",
    department: "Landes",
    lat: 43.670, lon: -1.440, offshore: 90,
    level: "advanced",
    type: "Beach break / fosse",
    description: "Le tube break le plus célèbre d'Europe. Étape WSL, vagues creuses et puissantes.",
  },
  {
    slug: "capbreton",
    name: "Capbreton - Le Santocha",
    shortName: "Capbreton",
    region: "Côte d'Argent",
    department: "Landes",
    lat: 43.645, lon: -1.447, offshore: 90,
    level: "intermediate",
    type: "Beach break / jetée",
    description: "Spot abrité par la jetée, fonctionne quand Hossegor sature. Belle vague droite.",
  },

  // Pays Basque
  {
    slug: "anglet",
    name: "Anglet - Chambre d'Amour",
    shortName: "Anglet",
    region: "Pays Basque",
    department: "Pyrénées-Atlantiques",
    lat: 43.485, lon: -1.550, offshore: 90,
    level: "intermediate",
    type: "Beach break",
    description: "Sept plages en enfilade. Très accessible, école et compétitions.",
  },
  {
    slug: "biarritz",
    name: "Biarritz - Côte des Basques",
    shortName: "Biarritz",
    region: "Pays Basque",
    department: "Pyrénées-Atlantiques",
    lat: 43.480, lon: -1.565, offshore: 110,
    level: "beginner",
    type: "Beach break",
    description: "Berceau du surf européen. Vague douce idéale pour le longboard et la progression.",
  },
  {
    slug: "guethary",
    name: "Guéthary - Parlementia",
    shortName: "Guéthary",
    region: "Pays Basque",
    department: "Pyrénées-Atlantiques",
    lat: 43.425, lon: -1.608, offshore: 135,
    level: "advanced",
    type: "Reef break",
    description: "Vague de récif puissante, pour confirmés uniquement quand ça envoie 3m+.",
  },
  {
    slug: "hendaye",
    name: "Hendaye",
    shortName: "Hendaye",
    region: "Pays Basque",
    department: "Pyrénées-Atlantiques",
    lat: 43.370, lon: -1.780, offshore: 180,
    level: "beginner",
    type: "Beach break",
    description: "Grande baie protégée, vagues douces. Le spot famille du Pays Basque.",
  },

  // Méditerranée
  {
    slug: "le-brusc",
    name: "Le Brusc - Six-Fours",
    shortName: "Le Brusc",
    region: "Méditerranée",
    department: "Var",
    lat: 43.066, lon: 5.805, offshore: 0,
    level: "intermediate",
    type: "Beach break",
    description: "Spot du Var qui fonctionne par tempête de SE/SW. Sessions rares mais belles.",
  },
  {
    slug: "marseille-prado",
    name: "Marseille - Le Prado",
    shortName: "Le Prado",
    region: "Méditerranée",
    department: "Bouches-du-Rhône",
    lat: 43.263, lon: 5.364, offshore: 0,
    level: "intermediate",
    type: "Beach break",
    description: "Plage urbaine de Marseille. Surfable quand le Mistral retombe et que la houle SW arrive.",
  },
  {
    slug: "almanarre",
    name: "L'Almanarre - Hyères",
    shortName: "Almanarre",
    region: "Méditerranée",
    department: "Var",
    lat: 43.084, lon: 6.137, offshore: 90,
    level: "intermediate",
    type: "Beach break",
    description: "Spot connu pour le windsurf mais surfable par tempête W. Cadre lagune.",
  },
];

export function getSpotBySlug(slug: string): Spot | undefined {
  return SPOTS.find((s) => s.slug === slug);
}
